# 站点
baseURL = 'https://hencte.pages.dev' # 请保证其链接完整性（即带有 htts://）
title = "亦幸小阁"
copyright = "版权所有"
sectionPagesMenu = "main"
languageCode = 'zh'

# 内容
defaultContentLanguage = 'zh'
hasCJKLanguage = true
enableEmoji = true
enableGitInfo = true
enableInlineShortcodes = true # Default value: false

