[goldmark.parser.attribute]
block = true # 通过在块下方防止 {.class-name} 来为代码块加一个类样式

# --------------e.g.
# > foo
# > bar
# {.myclass}

# - Fruit
#   - Apple
#   - Orange
#   - Banana
#   {.fruits}
# - Dairy
#   - Milk
#   - Cheese
#   {.dairies}
# {.list}
# --------------

# --------------e.g.
# ```go {.myclass linenos=table,hl_lines=[8,"15-17"],linenostart=199}
# // ... code
# ```

[goldmark.renderer]
  # hardWraps = true #  By default, Goldmark ignores newlines within a paragraph. Set to true to render newlines as <br> elements.